$(document).ready(function(){$("#player").html('<div id="jquery_jplayer"></div><div id="jp_container" class="player-container"><div class="first"><div class="jp-play">Play</div><div class="jp-pause1">Pause</div></div><div><div class="song">\u00c7\u00e0\u00e3\u00f0\u00f3\u00e7\u00ea\u00e0 \u00f2\u00f0\u00e5\u00ea\u00e0...</div><div class="jp-mute"></div><div class="jp-unmute"></div><div class="jp-volume-bar"><div class="jp-volume-bar-value"></div></div></div></div>');$(".song").marquee({speed:30})});
function getMyPlayer(b,d){var a=new Uri(b),f=a.host();if(0!=strpos(f,"radioheart.ru",0)){var k=a.port(),a=a.path();getstat(f,k,"/nonstop",a,"&track","","","","","","");setInterval("getstat('"+f+"', '"+k+"', '/nonstop', '"+a+"', '&track', '', '', '', '', '', '')",3E4);volume=0.3;volumeStep=0.1;$jPlayer=$("#jquery_jplayer");media={mp3:b};$jPlayer.jPlayer({ready:function(){"1"==d&&$("#jp_container .jp-play").click()},swfPath:"rh_player/js",cssSelectorAncestor:"#jp_container",supplied:"mp3",wmode:"window",
volume:volume,solution:"flash, html",backgroundColor:null});$("#jp_container .jp-play").click(function(){$jPlayer.jPlayer("setMedia",media);$jPlayer.jPlayer("play");$(this).fadeOut("fast",function(){$(".jp-pause1").fadeIn("fast")})});$("#jp_container .jp-pause1").click("fast",function(){$(this).fadeOut(function(){$(".jp-play").fadeIn("fast")});$jPlayer.jPlayer("stop")});$(".jp-volume-bar").slider({value:50,max:100,range:"min",animate:!0,orientation:"horizontal",slide:function(a,d){$jPlayer.jPlayer("volume",
d.value/100)}})}else $("#player").html("\u00d2\u00ee\u00eb\u00fc\u00ea\u00ee \u00e4\u00eb\u00ff \u00ea\u00eb\u00e8\u00e5\u00ed\u00f2\u00ee\u00e2 radioheart.ru!")}
var Query=function(b){var d;var a=b,b=[],f,k;if(!("undefined"===typeof a||null===a||""===a)){0===a.indexOf("?")&&(a=a.substring(1));f=a.toString().split(/[&;]/);for(a=0;a<f.length;a++)k=f[a],k=k.split("="),b.push([k[0],k[1]])}d=b;var h=function(a){a=decodeURIComponent(a);return a=a.replace("+"," ")},j=function(a,l){var e=[],i,g,b,f;for(i=0;i<d.length;i++)g=d[i],b=h(g[0])===h(a),f=h(g[1])===h(l),(1===arguments.length&&!b||2===arguments.length&&!b&&!f)&&e.push(g);d=e;return this},n=function(a,b,e){3===
arguments.length&&-1!==e?(e=Math.min(e,d.length),d.splice(e,0,[a,b])):0<arguments.length&&d.push([a,b]);return this};return{getParamValue:function(a){var b,e;for(e=0;e<d.length;e++)if(b=d[e],h(a)===h(b[0]))return b[1]},getParamValues:function(a){var b=[],e,i;for(e=0;e<d.length;e++)i=d[e],h(a)===h(i[0])&&b.push(i[1]);return b},deleteParam:j,addParam:n,replaceParam:function(a,b,e){var i=-1,g,f;if(3===arguments.length){for(g=0;g<d.length;g++)if(f=d[g],h(f[0])===h(a)&&decodeURIComponent(f[1])===h(e)){i=
g;break}j(a,e).addParam(a,b,i)}else{for(g=0;g<d.length;g++)if(f=d[g],h(f[0])===h(a)){i=g;break}j(a);n(a,b,i)}return this},toString:function(){var a="",b,e;for(b=0;b<d.length;b++)e=d[b],0<a.length&&(a+="&"),a+=e.join("=");return 0<a.length?"?"+a:a}}},Uri=function(b){for(var d="source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),b=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/.exec(b||
""),a={},f=14;f--;)a[d[f]]=b[f]||"";a.queryKey={};a[d[12]].replace(/(?:^|&)([^&=]*)=?([^&]*)/g,function(c,b,g){b&&(a.queryKey[b]=g)});var k=new Query(a.query),h=function(c){"undefined"!==typeof c&&(a.protocol=c);return a.protocol},j=null,n=function(c){"undefined"!==typeof c&&(j=c);return null===j?-1!==a.source.indexOf("//"):j},m=function(c){"undefined"!==typeof c&&(a.userInfo=c);return a.userInfo},l=function(c){"undefined"!==typeof c&&(a.host=c);return a.host},e=function(c){"undefined"!==typeof c&&
(a.port=c);return a.port},i=function(c){"undefined"!==typeof c&&(a.path=c);return a.path},g=function(c){"undefined"!==typeof c&&(k=new Query(c));return k},p=function(c){"undefined"!==typeof c&&(a.anchor=c);return a.anchor},q=function(){var c="",a=function(a){return null!==a&&""!==a};a(h())?(c+=h(),h().indexOf(":")!==h().length-1&&(c+=":"),c+="//"):n()&&a(l())&&(c+="//");a(m())&&a(l())&&(c+=m(),m().indexOf("@")!==m().length-1&&(c+="@"));a(l())&&(c+=l(),a(e())&&(c+=":"+e()));if(a(i()))c+=i();else if(a(l())&&
(a(g().toString())||a(p())))c+="/";a(g().toString())&&(0!==g().toString().indexOf("?")&&(c+="?"),c+=g().toString());a(p())&&(0!==p().indexOf("#")&&(c+="#"),c+=p());return c};return{protocol:h,hasAuthorityPrefix:n,userInfo:m,host:l,port:e,path:i,query:g,anchor:p,setProtocol:function(a){h(a);return this},setHasAuthorityPrefix:function(a){n(a);return this},setUserInfo:function(a){m(a);return this},setHost:function(a){l(a);return this},setPort:function(a){e(a);return this},setPath:function(a){i(a);return this},
setQuery:function(a){g(a);return this},setAnchor:function(a){p(a);return this},getQueryParamValue:function(a){return g().getParamValue(a)},getQueryParamValues:function(a){return g().getParamValues(a)},deleteQueryParam:function(a,b){2===arguments.length?g().deleteParam(a,b):g().deleteParam(a);return this},addQueryParam:function(a,b,d){3===arguments.length?g().addParam(a,b,d):g().addParam(a,b);return this},replaceQueryParam:function(a,b,d){3===arguments.length?g().replaceParam(a,b,d):g().replaceParam(a,
b);return this},toString:q,clone:function(){return new Uri(q())}}},jsUri=Uri;function strpos(b,d,a){b=b.indexOf(d,a);return 0<=b?b:!1}
(function(b){b.fn.textWidth=function(){var d='<span style="display:none">'+b(this).text()+"</span>";b("body").append(d);d=b("body").find("span:last").width();b("body").find("span:last").remove();return d};b.fn.marquee=function(d){function a(){if(!f.length)return i.reject();if(j==e){l++;if(l==d.count)return f.css(n),i.resolve();j=d.leftToRight?-1*k:h}f.css("text-indent",j+"px");d.leftToRight?j++:j--;setTimeout(a,d.speed)}var f=b(this),k=f.textWidth(),h=f.width(),j=h,n={"text-indent":f.css("text-indent"),
overflow:f.css("overflow"),"white-space":f.css("white-space")},m={"text-indent":j,overflow:"hidden","white-space":"nowrap"},d=b.extend(!0,{count:-1,speed:10,leftToRight:!1},d),l=0,e=-1*k,i=b.Deferred();d.leftToRight?(j=-1*k,j++,e=h):j--;f.css(m);a();return i.promise()}})(jQuery);
function getstat(b,d,a,f,k,h,j,n,m,l,e){$.getJSON("http://radioheart.ru/tools/mainstat1.php?ip="+b+"&port="+d+"&nonstop="+a+"&mount="+f+k+h+j+n+m+l+"&callback=?",function(a){var b="";void 0!=a.stream&&(b=a.stream+"<br />");void 0!=a.dj&&(b=b+"DJ: "+a.dj+"<br />");void 0!=a.listeners&&(b=b+a.listeners+"<br />");void 0!=a.mlisteners&&(b=b+a.mlisteners+"<br />");void 0!=a.track&&(b=b+a.track+"<br />");if(void 0!=a.lastsongs){var d=0,b=b+"\u00d0\u00a1\u00d0\u00bf\u00d0\u00b8\u00d1\u0081\u00d0\u00be\u00d0\u00ba \u00d0\u00bf\u00d0\u00be\u00d1\u0081\u00d0\u00bb\u00d0\u00b5\u00d0\u00b4\u00d0\u00bd\u00d0\u00b8\u00d1\u2026 \u00d0\u00bf\u00d0\u00b5\u00d1\u0081\u00d0\u00b5\u00d0\u00bd:";
for(d;d<a.lastsongs.length;d++)null!=a.lastsongs[d]&&(b=b+a.lastsongs[d]+"<br />")}$(".song").html(b);a='<img src="'+e+a.dj+'.jpg" />';$("#djavatar").html(a)})};